### ISSUE TITLE
ubuntu 20.04 and bitwig - no gui - black window

### ISSUE THREAD

**Issue by dreamcat4** [olegkapitonov/KPP-VST3#5]
Thanks so much for looking into this. Very grateful.

**Comment by olegkapitonov** [comment]
Hi, @dreamcat4!

Thank you.

I installed Ubuntu 20.04 in Virtualbox, then packages from the list in my README,
then BITWIG. Unpacked **KPP-1.2.1-binary-ubuntu-bionic.tar.bz2** into **/home/user/.vst3** folder as is.
After that I have plugins' GUI in BITWIG, all works on my setup.

Can you reproduce this bug on another machine or Virtualbox?
Do you have any other VST3 plugins, do they work on your system?

**Comment by dreamcat4** [comment]
> Can you reproduce this bug on another machine or Virtualbox?

Do not have another machine, nor Virtualbox. Don't have the time to set that up all in a new VM.

> Do you have any other VST3 plugins, do they work on your system?

I have Carla VST2 plugins. But also there is a cmdline program with bitwig called `bitwig-plugin-test`. Which is a standalone program, and it does not report any errors with your plugins. However the plugin window it launches is also always black / blank. Here is the log of that output:

https://gist.github.com/dreamcat4/f205985861fc00931f128e5409b5f864

I also have logged here the main bitwig program. However there is nothing generated in the bitwig log output when I am loading your plugin `kpp_tubeamp`. However here you can also see my exact version information at the top, which maybe could be helpful?

Bitwig log:

https://gist.github.com/dreamcat4/a44485ff8a1dbf400ad43c3808f3fbb4

Things I have tried, but did not help :(

* Re ran the APT command, to update all of the runtime dependancies listed in the README file. They are all installed
* Installed all the dev build deps too. No difference
* Disabled my other plugins folders `~/.lv2` and  `~/.ladspa`
* Updated the kernel to latest `v5.10.15`
* Updated ubuntu with software update
* Rebooted the computer
* Switched my DE from Budgie to Gnome (wayland)
* Looked for plugin error messages in Bitwig -> Settings -> Plugins, click "Show Plug-in errors" button
* Ran `strings` on the plugin file `kpp_tubeamp.so`, then re-created the folder `/home/curufinwe/.vst3` because it was referenced in the output of `strings`

Nothing has worked here for me.

Lets see now...  It seems to me that you are using: 

> 2. Cairo library for GUI.
> 6. gtkmm-3.0

Well what can i check there? For those above UI libraries?

Tried to build them from source just now. And it said:

```sh
[Accuracy: Sample, 1 Parameters, Change every100 Samples]
Info:  ===Accuracy: Sample, 1 Parameters, Change every100 Samples ====================================
Info:  64bit Audio Processing not supported.
[Succeeded]

-------------------------------------------------------------
Result: 47 tests passed, 0 tests failed
-------------------------------------------------------------
ln: /home/id/.vst3/kpp_fuzz.vst3: cannot overwrite directory
make[2]: *** [/home/id/Mega/dev/audio/KPP-VST3/build/kpp_fuzz/CMakeFiles/kpp_fuzz.dir/build.make:154: /home/id/Mega/dev/audio/VST_SDK/VST3_SDK/build/VST3/Release/kpp_fuzz.vst3/Contents/x86_64-linux/kpp_fuzz.so] Error 1
make[2]: *** Deleting file '/home/id/Mega/dev/audio/VST_SDK/VST3_SDK/build/VST3/Release/kpp_fuzz.vst3/Contents/x86_64-linux/kpp_fuzz.so'
make[1]: *** [CMakeFiles/Makefile2:1227: /home/id/Mega/dev/audio/KPP-VST3/build/kpp_fuzz/CMakeFiles/kpp_fuzz.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
θ88° [id:~/Mega/dev/audio/KPP-VST3/build] master 2 ± 
```

**Comment by olegkapitonov** [comment]
Hi, @dreamcat4!

Some good news. I reproduced this bug!

Not so good news - it's BITWIG problem, not KPP.

I installed BITWIG 3.0.2 and got black GUI windows. Another VST3 plugin (not KPP) 
that I tried also has a black window.

With the latest BITWIG 3.3.1 version all works fine.

I think that BITWIG 3.0.2 has some rendering problems on Ubuntu 20.04.
I can't do anything with it because the problem is obviously not in my code
but in VST3 Framework code or BITWIG.

You may try to rebuild the plugins but I don't think this will change anything.

>Tried to build them from source just now. And it said

/home/id/.vst3 folder should not exist before the build process starts. Build will create it
and make symlinks to plugins' folders there. Or at least this folder should be empty before the build starts.

**Comment by dreamcat4** [comment]
Thank you so much! This is a great news, to understand what the problem is. Really I shall just have to upgrade and that should also help compatibility with any other vsts. Really I am so grateful to know this. Because often it's hard to know what to do when finding a plugin has failed.

Closing this issue.
